### ISSUE TITLE
Possible Windows 11 issue

### ISSUE THREAD

**Issue by Yattabyte** [manshanko/dtkit-patch#1]
Walked a buddy of mine through the same steps I did to install, however he got this error so I figure it was due to it being windows 11. If this error isn't due to that then close the issue and sorry for the false report. In case it helps, its the Xbox app version of the game.

```txt
failed to read "bundle_database.data"
Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
Error patching the Darktide bundle database. See logs.
```

**Comment by manshanko** [comment]
Someone also reported it in the DMF discord. They fixed it by reinstalling [DML](https://www.nexusmods.com/warhammer40kdarktide/mods/19) ([Github](https://github.com/Darktide-Mod-Framework/Darktide-Mod-Loader)).

I looked into it some but it's not clear what could be causing the issue.
