### ISSUE TITLE
'The system cannot find the path specified' when running 'toggle_darktide_mods.bat'

### ISSUE THREAD

**Issue by Totenius** [manshanko/dtkit-patch#2]
When trying to run 'toggle_darktide_mods.bat' I get the following error:

```
"starting darktide patcher..
The system cannot find the path specified.
Error patching the darktide bundle database. see logs.
press any key to continue..."
```

The logs are showing an error with dtkit-patch.exe when initially running the batch file - I thought at first the issue may have been my steam games being installed on a partition other than C but I'm really not sure.

```
Faulting application name: dtkit-patch.exe, version: 0.0.0.0, time stamp: 0x63fbeb4f
Faulting module name: dtkit-patch.exe, version: 0.0.0.0, time stamp: 0x63fbeb4f
Exception code: 0xc000001d
Fault offset: 0x0000000000001d55
Faulting process ID: 0x4590
Faulting application start time: 0x01d954f9272466ed
Faulting application path: H:\Steam\steamapps\common\Warhammer 40,000 DARKTIDE\tools\dtkit-patch.exe
Faulting module path: H:\Steam\steamapps\common\Warhammer 40,000 DARKTIDE\tools\dtkit-patch.exe
Report ID: feba719c-689d-47b6-a139-9dea6d609711
Faulting package full name: 
Faulting package-relative application ID: 
```

I have previously tried reverifying the game files and reinstalling the loader - when I ran the batch file for the second time I didn't get the prompt to unpatch.

**Comment by manshanko** [comment]
Strange. This looks related to a few other reports on the modders discord. While I haven't reproduced it, deluxghost has been very helpful in narrowing it down to a possible build misconfiguration. Let me know if replacing `tools\dtkit-patch.exe` with `dtkit-patch_alt.exe` from release 0.1.4 ([direct download](https://github.com/ManShanko/dtkit-patch/releases/download/0.1.4/dtkit-patch_alt.exe)) fixes your problem.

**Comment by Totenius** [comment]
Hi! Sorry for the delay, I've not been able to play the game for a few weeks. The release 0.1.4 executable has worked! Thanks very much!
